#dao/__init__.py

from .dao import DAO, DAOException